name: OIDC Integration with Artifactory (hts2)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  JF_URL: ${{ vars.JF_URL }}

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Set up JFrog CLI
        uses: jfrog/setup-jfrog-cli@v4
        with:
          oidc-provider-name: reddappag
          oidc-audience: reddappag

      - name: Configure npm registry
        run: |
          jf npm-config \
            --repo-resolve=rg-gactions-npm \
            --repo-deploy=rg-gactions-npm

      - name: Install dependencies
        run: |
          jf npm install \
           

      - name: Build the project
        run: jf npm run build

      - name: Upload build artifacts to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: dist/**/*

      - name: Publish npm package to Artifactory
        run: |
          jf npm publish \
            --build-name=red-new \
            --build-number=${{ github.run_number }}

      - name: Publish Build Info
        run: |
          jf rt build-publish \
            red-new \
            ${{ github.run_number }} \
            --project rg
